"""GitHub App Installation Access Token Credential Plugin.

This module defines a credential plugin for making use of the
GitHub Apps mechanism, allowing authentication via GitHub App
installation-scoped access tokens.

Functions:

- :func:`extract_github_app_install_token`: Generates a GitHub App
  Installation token.
- ``github_app_lookup``: Defines the credential plugin interface.
"""

from github import Auth as Auth, Github
from github.Consts import DEFAULT_BASE_URL as PUBLIC_GH_API_URL
from github.GithubException import (
    BadAttributeException,
    GithubException,
    UnknownObjectException,
)

from typing import TypedDict, Unpack
from django.utils.translation import gettext_lazy as _

from .plugin import CredentialPlugin

github_app_inputs = {
    'fields': [
        {
            'id': 'github_api_url',
            'label': _('GitHub API endpoint URL'),
            'type': 'string',
            'help_text': _(
                'Specify the GitHub API URL here. In the case of an Enterprise: '
                'https://gh.your.org/api/v3 (self-hosted) '
                'or https://api.SUBDOMAIN.ghe.com (cloud)',
            ),
            'default': 'https://api.github.com',
        },
        {
            'id': 'app_or_client_id',
            'label': _('GitHub App ID or Client ID'),
            'type': 'string',
            'help_text': _(
                'The GitHub App ID or Client ID created by the GitHub Admin. '
                'Example App ID: 1121547, Client ID: Iv23likIfIXeZTb5GCAA '
                'found on https://github.com/settings/apps/ '
                'required for creating a JWT token for authentication.',
            ),
        },
        {
            'id': 'install_id',
            'label': _('GitHub App Installation ID'),
            'type': 'string',
            'help_text': _(
                'The Installation ID from the GitHub App installation '
                'generated by the GitHub Admin. '
                'Example: 59980338 extracted from the installation link '
                'https://github.com/settings/installations/59980338 '
                'required for creating a limited GitHub app token.',
            ),
        },
        {
            'id': 'private_rsa_key',
            'label': _('RSA Private Key'),
            'type': 'string',
            'format': 'ssh_private_key',
            'secret': True,
            'multiline': True,
            'help_text': _(
                'Paste the contents of the PEM file that the GitHub Admin provided to you with the app and installation IDs.',
            ),
        },
    ],
    'metadata': [
        {
            'id': 'description',
            'label': _('Description (Optional)'),
            'type': 'string',
            'help_text': _('To be removed after UI is updated'),
        },
    ],
    'required': ['app_or_client_id', 'install_id', 'private_rsa_key'],
}


class EmptyKwargs(TypedDict):
    """Schema for zero keyword arguments."""


def extract_github_app_install_token(  # noqa: WPS210
    *,
    github_api_url: str,
    app_or_client_id: int | str,
    private_rsa_key: str,
    install_id: int | str,
    **_discarded_kwargs: Unpack[EmptyKwargs],
) -> str:
    """Generate a GH App Installation access token.

    :param github_api_url: The GitHub instance API endpoint URL.
    :param app_or_client_id: The GitHub App ID or Client ID.
    :param private_rsa_key: The private key associated with the GitHub
        App.
    :param install_id: The GitHub App Installation ID.
    :param _discarded_kwargs: Aren't expected to be passed.
    :returns: A GitHub access token for a GitHub App Installation.
    :raises ValueError: If authentication fails or parameters are invalid.
    :raises RuntimeError: If an unexpected error occurs during token generation.
    """
    auth = Auth.AppAuth(
        app_id=str(app_or_client_id),
        private_key=private_rsa_key,
    ).get_installation_auth(installation_id=int(install_id))

    Github(
        auth=auth,
        base_url=github_api_url if github_api_url else PUBLIC_GH_API_URL,
    )

    doc_url = 'See https://docs.github.com/rest/reference/apps#create-an-installation-access-token-for-an-app'
    app_install_context = f'app_or_client_id: {app_or_client_id}, install_id: {install_id}'

    try:
        return auth.token
    except UnknownObjectException as github_install_not_found_exc:
        raise ValueError(
            f'Failed to retrieve a GitHub installation token from {github_api_url} using {app_install_context}. Is the app installed? {doc_url}.'
            f'\n\n{github_install_not_found_exc}',
        ) from github_install_not_found_exc
    except GithubException as pygithub_catchall_exc:
        raise RuntimeError(
            f'An unexpected error happened while talking to GitHub API @ {github_api_url} ({app_install_context}). '
            f'Is the app or client ID correct? And the private RSA key? {doc_url}.'
            f'\n\n{pygithub_catchall_exc}',
        ) from pygithub_catchall_exc
    except BadAttributeException as github_broken_exc:
        raise RuntimeError(
            f'Broken GitHub @ {github_api_url} with {app_install_context}. It is a bug, please report it to the developers.\n\n{github_broken_exc}',
        ) from github_broken_exc


github_app_lookup_plugin = CredentialPlugin(
    'GitHub App Installation Access Token Lookup',
    inputs=github_app_inputs,
    backend=extract_github_app_install_token,
)
